In [3]:
cd /content/drive/MyDrive/IDM_Project/idm-data-project/

/content/drive/MyDrive/IDM_Project/idm-data-project


In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import os
from getpass import getpass
import urllib

user = input('User name: ')
password = getpass('Password: ')
password = urllib.parse.quote(password) # password is converted into url format
repo_name = input('Repo name: ')

cmd_string = 'git pull https://{0}:{1}@github.com/makfordead/{2}.git'.format(user, password, repo_name)

os.system(cmd_string)
cmd_string, password = "", "" # removing the password from the variable

User name: makfordead
Password: ··········


In [4]:
!git config --global user.email "murtaza.kazmi.75@gmail.com"
!git config --global user.name "Murtaza-Kazmi"

In [ ]:
!git add .
!git commit -m "many different models predicted; added experiment for best predictor selection"
!git push

# Imports

In [6]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [47]:
df = pd.read_csv('allbp-data.csv')
test = pd.read_csv('allbp-test.csv')

# Data Understanding

In [8]:
df.describe()

age   sex on thyroxine  ...   TBG referral source          class
count   2800  2800         2800  ...  2800            2800           2800
unique    94     3            2  ...     1               5           2800
top       59     F            f  ...     ?           other  negative.|130
freq      75  1830         2470  ...  2800            1632              1

[4 rows x 30 columns]

In [9]:
df.head(10)

age sex on thyroxine  ... TBG referral source           class
0  41   F            f  ...   ?            SVHC  negative.|3733
1  23   F            f  ...   ?           other  negative.|1442
2  46   M            f  ...   ?           other  negative.|2965
3  70   F            t  ...   ?           other   negative.|806
4  70   F            f  ...   ?             SVI  negative.|2807
5  18   F            t  ...   ?           other  negative.|3434
6  59   F            f  ...   ?           other  negative.|1595
7  80   F            f  ...   ?             SVI  negative.|1367
8  66   F            f  ...   ?             SVI  negative.|1787
9  68   M            f  ...   ?             SVI  negative.|2534

[10 rows x 30 columns]

In [42]:
test.head()

age sex on thyroxine  ... TBG referral source     class
0   35   F            f  ...   ?           other  negative
1   63   M            f  ...   ?             SVI  negative
2   25   F            f  ...   ?            SVHD  negative
3   53   F            f  ...   ?           other  negative
4   92   F            f  ...   ?             SVI  negative

[5 rows x 30 columns]

In [41]:
test.describe()

age
count  972.000000
mean    51.423868
std     18.966700
min      7.000000
25%     35.000000
50%     54.000000
75%     67.000000
max     93.000000

# Data Preparation

In [48]:
df['class'] = df['class'].apply(lambda x: x[:x.find('.')])

In [49]:
test['class'] = test['class'].apply(lambda x: x[:x.find('.')])

In [50]:
test.head(10)

age sex on thyroxine  ... TBG referral source     class
0   35   F            f  ...   ?           other  negative
1   63   M            f  ...   ?             SVI  negative
2   25   F            f  ...   ?            SVHD  negative
3   53   F            f  ...   ?           other  negative
4   92   F            f  ...   ?             SVI  negative
5   67   M            f  ...   ?           other  negative
6   60   F            f  ...   ?           other  negative
7   60   F            f  ...   ?             SVI  negative
8   48   F            f  ...   ?           other  negative
9   27   F            f  ...   ?             SVI  negative

[10 rows x 30 columns]

In [51]:
df.head(10)

age sex on thyroxine  ... TBG referral source     class
0  41   F            f  ...   ?            SVHC  negative
1  23   F            f  ...   ?           other  negative
2  46   M            f  ...   ?           other  negative
3  70   F            t  ...   ?           other  negative
4  70   F            f  ...   ?             SVI  negative
5  18   F            t  ...   ?           other  negative
6  59   F            f  ...   ?           other  negative
7  80   F            f  ...   ?             SVI  negative
8  66   F            f  ...   ?             SVI  negative
9  68   M            f  ...   ?             SVI  negative

[10 rows x 30 columns]

In [52]:
df.dropna().count()

age                          2800
sex                          2800
on thyroxine                 2800
query on thyroxine           2800
on antithyroid medication    2800
sick                         2800
pregnant                     2800
thyroid surgery              2800
I131 treatment               2800
query hypothyroid            2800
query hyperthyroid           2800
lithium                      2800
goitre                       2800
tumor                        2800
hypopituitary                2800
psych                        2800
TSH measured                 2800
TSH                          2800
T3 measured                  2800
T3                           2800
TT4 measured                 2800
TT4                          2800
T4U measured                 2800
T4U                          2800
FTI measured                 2800
FTI                          2800
TBG measured                 2800
TBG                          2800
referral source              2800
class         

In [ ]:
# df = pd.read_csv('allbp-data.csv')
# test = pd.read_csv('allbp-test.csv')

In [53]:
df['TBG'].unique()

array(['?'], dtype=object)

In [54]:
test['TBG'].unique()

array(['?'], dtype=object)

In [55]:
df.drop(columns='TBG', inplace = True)
test.drop(columns='TBG', inplace = True)

In [57]:
for col in df.columns:
    df.drop(df[df[col] == '?'].index, inplace = True)

In [61]:
for col in test.columns:
    test.drop(test[test[col] == '?'].index, inplace = True)

In [58]:
df.describe()

age   sex on thyroxine  ... TBG measured referral source     class
count   1947  1947         1947  ...         1947            1947      1947
unique    91     2            2  ...            1               5         3
top       59     F            f  ...            f           other  negative
freq      59  1282         1764  ...         1947             892      1841

[4 rows x 29 columns]

In [18]:
df.head()

age sex on thyroxine  ... TBG measured referral source     class
0  41   F            f  ...            f            SVHC  negative
4  70   F            f  ...            f             SVI  negative
7  80   F            f  ...            f             SVI  negative
8  66   F            f  ...            f             SVI  negative
9  68   M            f  ...            f             SVI  negative

[5 rows x 29 columns]

In [62]:
test.describe()

age
count  696.000000
mean    52.705460
std     18.864173
min      7.000000
25%     37.000000
50%     55.000000
75%     68.000000
max     93.000000

In [63]:
print(972-696, "decreased from test data which originally had 972. Now 696")

276 decreased from test data which originally had 972. Now 696


In [64]:
test.head()

age sex on thyroxine  ... TBG measured referral source     class
1   63   M            f  ...            f             SVI  negative
2   25   F            f  ...            f            SVHD  negative
3   53   F            f  ...            f           other  negative
4   92   F            f  ...            f             SVI  negative
6   60   F            f  ...            f           other  negative

[5 rows x 29 columns]

In [65]:
for col in df.columns:
    if not col in ['age', 'TSH', 'T3', 'TT4', 'T4U', 'FTI']:
      median = df[col].describe().top
      df[col] = df[col].apply(lambda x: median if x == '?' else x)

In [66]:
for col in df.columns:
    if col in ['age', 'TSH', 'T3', 'TT4', 'T4U', 'FTI']:
      df[col] = df[col].apply(lambda x: 0 if x == '?' else x)

for col in df.columns:
    if col in ['age', 'TSH', 'T3', 'TT4', 'T4U', 'FTI']:
      df[col] = df[col].apply(lambda x: 0 if x == '?' else x)

In [67]:
for col in test.columns:
    if not col in ['age', 'TSH', 'T3', 'TT4', 'T4U', 'FTI']:
      median = test[col].describe().top
      test[col] = test[col].apply(lambda x: median if x == '?' else x)

In [68]:
for col in test.columns:
    if col in ['age', 'TSH', 'T3', 'TT4', 'T4U', 'FTI']:
      test[col] = test[col].apply(lambda x: 0 if x == '?' else x)

for col in test.columns:
    if col in ['age', 'TSH', 'T3', 'TT4', 'T4U', 'FTI']:
      test[col] = test[col].apply(lambda x: 0 if x == '?' else x)

In [69]:
X = df.drop(columns='class')

In [70]:
X_test = test.drop(columns='class')

In [45]:
X.head()

age sex on thyroxine  ...  FTI TBG measured referral source
0  41   1            1  ...  109            1               0
4  70   1            1  ...   70            1               2
7  80   1            1  ...  115            1               2
8  66   1            1  ...  132            1               2
9  68   0            1  ...   93            1               2

[5 rows x 28 columns]

In [71]:
for col in X.columns:
  if not col in ['sex','age', 'TSH', 'T3', 'TT4', 'T4U', 'FTI', 'TBG', 'referral source']:
    X[col] = X[col].apply(lambda x: 1 if x == 'f' else '0')

X['sex'] = X['sex'].apply(lambda x: 1 if x == 'F' else '0')

In [72]:
X['referral source'].unique()

array(['SVHC', 'SVI', 'other', 'SVHD', 'STMW'], dtype=object)

In [73]:
X['referral source'] = X['referral source'].apply(lambda x: 0 if x == 'SVHC' else (1 if x == 'other' else (2 if x == 'SVI' else (3 if x == 'STMW' else 4))))

In [74]:
for col in X_test.columns:
  if not col in ['sex','age', 'TSH', 'T3', 'TT4', 'T4U', 'FTI', 'TBG', 'referral source']:
    X_test[col] = X_test[col].apply(lambda x: 1 if x == 'f' else '0')

X_test['sex'] = X_test['sex'].apply(lambda x: 1 if x == 'F' else '0')

In [75]:
X_test['referral source'].unique()

array(['SVI', 'SVHD', 'other', 'SVHC', 'STMW'], dtype=object)

In [76]:
X_test['referral source'] = X_test['referral source'].apply(lambda x: 0 if x == 'SVHC' else (1 if x == 'other' else (2 if x == 'SVI' else (3 if x == 'STMW' else 4))))

In [25]:
X.head()

age sex on thyroxine  ...  FTI TBG measured referral source
0  41   1            1  ...  109            1               0
4  70   1            1  ...   70            1               2
7  80   1            1  ...  115            1               2
8  66   1            1  ...  132            1               2
9  68   0            1  ...   93            1               2

[5 rows x 28 columns]

In [77]:
X_test.head()

age sex on thyroxine  ...  FTI TBG measured referral source
1   63   0            1  ...  113            1               2
2   25   1            1  ...   75            1               4
3   53   1            1  ...  141            1               1
4   92   1            1  ...  143            1               2
6   60   1            1  ...   90            1               1

[5 rows x 28 columns]

In [78]:
X_train = X

In [26]:
y = df['class']

In [27]:
y = y.apply(lambda x: 0 if x == 'negative' else (1 if x == 'increased binding protein' else 2))

In [79]:
y_train = y

In [80]:
y_test = test['class']

In [81]:
y_test = y_test.apply(lambda x: 0 if x == 'negative' else (1 if x == 'increased binding protein' else 2))

In [82]:
y_train.head()

0    0
4    0
7    0
8    0
9    0
Name: class, dtype: int64

In [83]:
y_test.head()

1    0
2    0
3    0
4    0
6    0
Name: class, dtype: int64

In [84]:
#X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 1, test_size = 0.3, shuffle=False)

# Modelling

In [29]:
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
import re
import spacy
from gensim.parsing.preprocessing import remove_stopwords
import gensim

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import ComplementNB
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import CategoricalNB
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import RepeatedStratifiedKFold
from scipy.stats import loguniform

 
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [30]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

# MultinomialNB

In [85]:
nb = MultinomialNB()
nb.fit(X_train, y_train)
nb_pred = nb.predict(X_test)
accuracy_score(y_test, nb_pred)

0.8017241379310345

In [86]:
model = MultinomialNB()
space = dict()
space['alpha'] = [i for i in range(1, 1000, 10)]
# define search
search = GridSearchCV(model, space, scoring='accuracy', n_jobs=-1)
# execute search
result = search.fit(X_train, y_train)
# summarize result
print('Best Score: %s' % result.best_score_)
print('Best Hyperparameters: %s' % result.best_params_)

Best Score: 0.9496671280732978
Best Hyperparameters: {'alpha': 131}


In [87]:
print("Classification Report:")
logistic_class_report = classification_report(y_test, result.predict(X_test))
print(logistic_class_report)

Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.96      0.97       674
           1       0.29      0.28      0.29        18
           2       0.00      0.00      0.00         4

    accuracy                           0.94       696
   macro avg       0.42      0.41      0.42       696
weighted avg       0.95      0.94      0.95       696



# BernoulliNB

In [88]:
model = BernoulliNB()
space = dict()
space['alpha'] = [0.1, 0.2, 0.5, 0.8, 1.0, 1.2, 1.4, 1.6, 2.0, 2.2, 2.4, 2.6, 2.8,3.0, 3.1,3.2,3.3,3.4]
# define search
search = GridSearchCV(model, space, scoring='accuracy', n_jobs=-1)
# execute search
result = search.fit(X_train, y_train)
# summarize result
print('Best Score: %s' % result.best_score_)
print('Best Hyperparameters: %s' % result.best_params_)

Best Score: 0.9517210467339001
Best Hyperparameters: {'alpha': 0.8}


# ComplementNB

In [89]:
model = ComplementNB()
space = dict()
space['alpha'] = [0.1,0.15,0.17, 0.19, 0.2,0.21,0.22, 0.23, 0.24,0.25,0.27, 0.28, 0.29,0.3, 0.5, 0.8, 1.0, 1.2, 1.4, 1.6, 2.0,2.1, 2.2, 2.4, 2.6, 2.8,2.9,3.0, 3.1, 3.2, 3.4, 3.6, 3.8, 3.9,4.0, 4.1, 4.2, 4.3, 4.4, 4.6, 4.8,4.9,5.0,5.1,5.2,5.3, 5.4, 5.5, 5.6, 5.7, 6, 6.4, 6.8, 7.2, 7.4, 7.8, 8.2]
# define search
search = GridSearchCV(model, space, scoring='accuracy', n_jobs=-1)
# execute search
result = search.fit(X_train, y_train)
# summarize result
print('Best Score: %s' % result.best_score_)
print('Best Hyperparameters: %s' % result.best_params_)

Best Score: 0.781203612154769
Best Hyperparameters: {'alpha': 8.2}


In [90]:
print("Classification Report:")
logistic_class_report = classification_report(y_test, result.predict(X_test))
print(logistic_class_report)

Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.78      0.87       674
           1       0.10      0.89      0.17        18
           2       0.00      0.00      0.00         4

    accuracy                           0.78       696
   macro avg       0.36      0.56      0.35       696
weighted avg       0.96      0.78      0.85       696



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# GaussianNB

In [93]:
nb = GaussianNB()
nb.fit(X_train, y_train)
nb_pred = nb.predict(X_test)
accuracy_score(y_test, nb_pred)

0.1724137931034483

In [95]:
print("Classification Report:")
logistic_class_report = classification_report(y_test, nb.predict(X_test))
print(logistic_class_report)

Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.15      0.26       674
           1       0.10      0.78      0.18        18
           2       0.01      1.00      0.02         4

    accuracy                           0.17       696
   macro avg       0.37      0.64      0.15       696
weighted avg       0.96      0.17      0.26       696



# CategoricalNB

In [98]:
model = CategoricalNB()
space = dict()
space['alpha'] = [0.1,0.15,0.17, 0.19, 0.2,0.21,0.22, 0.23, 0.24,0.25,0.27, 0.28, 0.29,0.3, 0.5, 0.8, 1.0, 1.2, 1.4, 1.6, 2.0,2.1, 2.2, 2.4, 2.6, 2.8,2.9,3.0, 3.1, 3.2, 3.4, 3.6, 3.8, 3.9,4.0, 4.1, 4.2, 4.3, 4.4, 4.6, 4.8,4.9,5.0,5.1,5.2,5.3, 5.4, 5.5, 5.6, 5.7, 6, 6.4, 6.8, 7.2, 7.4, 7.8, 8.2]
# define search
search = GridSearchCV(model, space, scoring='accuracy', n_jobs=-1)
# execute search
result = search.fit(X_train, y_train)
# summarize result
print('Best Score: %s' % result.best_score_)
print('Best Hyperparameters: %s' % result.best_params_)

IndexError: ignored

In [ ]:
print("Classification Report:")
logistic_class_report = classification_report(y_test, result.predict(X_test))
print(logistic_class_report)

# Random Forest and Gradient Boosted Trees

In [99]:
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt','log2']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 1000,10)]
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10,14]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4,6,8]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
              'criterion':['entropy','gini']}
print(random_grid)

{'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000], 'max_features': ['auto', 'sqrt', 'log2'], 'max_depth': [10, 120, 230, 340, 450, 560, 670, 780, 890, 1000], 'min_samples_split': [2, 5, 10, 14], 'min_samples_leaf': [1, 2, 4, 6, 8], 'criterion': ['entropy', 'gini']}


In [101]:
rf=RandomForestClassifier()

In [102]:

rf_randomcv=RandomizedSearchCV(estimator=rf,param_distributions=random_grid,n_iter=100,cv=5,verbose=2,
                               random_state=100,n_jobs=-1)
### fit the randomized model
rf_randomcv.fit(X_train,y_train)

Fitting 5 folds for each of 100 candidates, totalling 500 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  37 tasks      | elapsed:  1.4min
[Parallel(n_jobs=-1)]: Done 158 tasks      | elapsed:  4.3min
[Parallel(n_jobs=-1)]: Done 361 tasks      | elapsed: 11.8min
[Parallel(n_jobs=-1)]: Done 500 out of 500 | elapsed: 16.5min finished


RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=RandomForestClassifier(bootstrap=True,
                                                    ccp_alpha=0.0,
                                                    class_weight=None,
                                                    criterion='gini',
                                                    max_depth=None,
                                                    max_features='auto',
                                                    max_leaf_nodes=None,
                                                    max_samples=None,
                                                    min_impurity_decrease=0.0,
                                                    min_impurity_split=None,
                                                    min_samples_leaf=1,
                                                    min_samples_split=2,
                                                    min_weight_fraction_leaf=0.0,
               

In [103]:
rf_randomcv.best_params_

{'criterion': 'gini',
 'max_depth': 230,
 'max_features': 'sqrt',
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'n_estimators': 1400}

In [104]:
best_random_grid=rf_randomcv.best_estimator_

In [105]:

y_pred=best_random_grid.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print("Accuracy Score {}".format(accuracy_score(y_test,y_pred)))
print("Classification report: {}".format(classification_report(y_test,y_pred)))

[[665   9   0]
 [  5  13   0]
 [  4   0   0]]
Accuracy Score 0.9741379310344828
Classification report:               precision    recall  f1-score   support

           0       0.99      0.99      0.99       674
           1       0.59      0.72      0.65        18
           2       0.00      0.00      0.00         4

    accuracy                           0.97       696
   macro avg       0.53      0.57      0.55       696
weighted avg       0.97      0.97      0.97       696



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [106]:

param_grid = {
    'criterion': [rf_randomcv.best_params_['criterion']],
    'max_depth': [rf_randomcv.best_params_['max_depth']],
    'max_features': [rf_randomcv.best_params_['max_features']],
    'min_samples_leaf': [rf_randomcv.best_params_['min_samples_leaf'], 
                         rf_randomcv.best_params_['min_samples_leaf']+2, 
                         rf_randomcv.best_params_['min_samples_leaf'] + 4],
    'min_samples_split': [rf_randomcv.best_params_['min_samples_split'] - 2,
                          rf_randomcv.best_params_['min_samples_split'] - 1,
                          rf_randomcv.best_params_['min_samples_split'], 
                          rf_randomcv.best_params_['min_samples_split'] +1,
                          rf_randomcv.best_params_['min_samples_split'] + 2],
    'n_estimators': [rf_randomcv.best_params_['n_estimators'] - 200, rf_randomcv.best_params_['n_estimators'] - 100, 
                     rf_randomcv.best_params_['n_estimators'], 
                     rf_randomcv.best_params_['n_estimators'] + 100, rf_randomcv.best_params_['n_estimators'] + 200]
}

print(param_grid)

{'criterion': ['gini'], 'max_depth': [230], 'max_features': ['sqrt'], 'min_samples_leaf': [1, 3, 5], 'min_samples_split': [0, 1, 2, 3, 4], 'n_estimators': [1200, 1300, 1400, 1500, 1600]}


In [107]:
rf=RandomForestClassifier()
grid_search=GridSearchCV(estimator=rf,param_grid=param_grid,cv=10,n_jobs=-1,verbose=2)
grid_search.fit(X_train,y_train)

Fitting 10 folds for each of 75 candidates, totalling 750 fits


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:667: UserWarning: The least populated class in y has only 7 members, which is less than n_splits=10.
  % (min_groups, self.n_splits)), UserWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  37 tasks      | elapsed:   18.4s
[Parallel(n_jobs=-1)]: Done 158 tasks      | elapsed:  3.3min
[Parallel(n_jobs=-1)]: Done 361 tasks      | elapsed:  8.5min
[Parallel(n_jobs=-1)]: Done 644 tasks      | elapsed: 17.2min
[Parallel(n_jobs=-1)]: Done 750 out of 750 | elapsed: 22.0min finished


GridSearchCV(cv=10, error_score=nan,
             estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                              class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              max_samples=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=100, n_jobs=None,
                                              oob_score=False,
                                              rand

In [108]:
best_grid=grid_search.best_estimator_
print(best_grid)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=230, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1300,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)


In [109]:
y_pred=best_grid.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print("Accuracy Score {}".format(accuracy_score(y_test,y_pred)))
print("Classification report: {}".format(classification_report(y_test,y_pred)))

[[666   8   0]
 [  5  13   0]
 [  4   0   0]]
Accuracy Score 0.9755747126436781
Classification report:               precision    recall  f1-score   support

           0       0.99      0.99      0.99       674
           1       0.62      0.72      0.67        18
           2       0.00      0.00      0.00         4

    accuracy                           0.98       696
   macro avg       0.54      0.57      0.55       696
weighted avg       0.97      0.98      0.97       696



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
rf=RandomForestClassifier()
grid_search=GridSearchCV(estimator=rf,param_grid=param_grid,cv=10,n_jobs=-1,verbose=2)
grid_search.fit(X_train,y_train)

In [110]:
#Gradient Boosting

gb = GradientBoostingClassifier(n_estimators=1000, learning_rate=0.24)
gb.fit(X_train, y_train)
gb_pred = gb.predict(X_test)
accuracy_score(y_test, gb_pred)

0.978448275862069

# Experiment

In [111]:
import seaborn as sns
import warnings
from sklearn import linear_model, tree, discriminant_analysis, naive_bayes, ensemble, gaussian_process
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold, cross_val_score, GridSearchCV
from sklearn.metrics import log_loss, confusion_matrix
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', 100)

In [112]:
classifiers = [

    #GLM
    linear_model.LogisticRegressionCV(),

    #Navies Bayes
    naive_bayes.BernoulliNB(),
    naive_bayes.GaussianNB(),

    #Discriminant Analysis
    discriminant_analysis.LinearDiscriminantAnalysis(),
    discriminant_analysis.QuadraticDiscriminantAnalysis(),

    #Ensemble Methods
    ensemble.AdaBoostClassifier(),
    ensemble.BaggingClassifier(),
    ensemble.ExtraTreesClassifier(),
    ensemble.GradientBoostingClassifier(),
    ensemble.RandomForestClassifier(),

    #Gaussian Processes
    gaussian_process.GaussianProcessClassifier(),

    #xgboost: http://xgboost.readthedocs.io/en/latest/model.html
#     xgb.XGBClassifier()    
]

In [113]:
def find_best_algorithms(classifier_list, X, y):
    # This function is adapted from https://www.kaggle.com/yassineghouzam/titanic-top-4-with-ensemble-modeling
    # Cross validate model with Kfold stratified cross validation
    kfold = StratifiedKFold(n_splits=5)

    # Grab the cross validation scores for each algorithm
    cv_results = [cross_val_score(classifier, X, y, scoring = "neg_log_loss", cv = kfold) for classifier in classifier_list]
    cv_means = [cv_result.mean() * -1 for cv_result in cv_results]
    cv_std = [cv_result.std() for cv_result in cv_results]
    algorithm_names = [alg.__class__.__name__ for alg in classifiers]

    # Create a DataFrame of all the CV results
    cv_results = pd.DataFrame({
        "Mean Log Loss": cv_means,
        "Log Loss Std": cv_std,
        "Algorithm": algorithm_names
    }).sort_values(by='Mean Log Loss')
    return cv_results

In [ ]:
algorithm_results = find_best_algorithms(classifiers, X, y)

In [ ]:
print(algorithm_results)

# Evaluation